# Generated by Django 5.0.2 on 2024-12-22 16:42

import base.models
import django_jalali.db.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_gender', models.BooleanField(blank=True, choices=[(True, 'آقا'), (False, 'خانم')], default=True, null=True, verbose_name='جنسیت')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('image', models.ImageField(max_length=255, upload_to=base.models.get_file_path, verbose_name='عکس پروفایل')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='شماره همراه')),
                ('name', models.CharField(max_length=255, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=255, verbose_name='رمز عبور')),
                ('national_code', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
            ],
        ),
    ]
