# Generated by Django 5.0.2 on 2024-12-23 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRequestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='male_gender',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='mobile',
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default='ali', max_length=255, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='interception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='alavi', max_length=255, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='limit_devices',
            field=models.PositiveSmallIntegerField(choices=[(1, 'اپلیکیشن وب (pwa)'), (2, 'اپلیکیشن اندروید'), (3, 'هر دو نوع دستگاه (وب و اندروید)'), (4, 'دستگاه حضور و غیاب')], default=1),
        ),
        migrations.AddField(
            model_name='staff',
            name='personnel_code',
            field=models.CharField(default='0', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='use_gps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='use_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='work_policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employer.workpolicy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='work_shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employer.workshift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='workplace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employer.workplace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='national_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='کد ملی'),
        ),
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.staff')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.staffrequestcategory')),
            ],
        ),
    ]
