# Generated by Django 5.0.2 on 2024-12-23 15:31

import base.models
import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import phonenumber_field.modelfields
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDeviceBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', django_jalali.db.models.jDateField()),
                ('floating_time', models.PositiveSmallIntegerField()),
                ('daily_overtime_limit', models.PositiveSmallIntegerField()),
                ('beginning_overtime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('middle_overtime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ending_overtime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('permitted_delay', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('permitted_acceleration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pre_shift_floating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('permitted_traffic_start', models.TimeField(blank=True, null=True)),
                ('permitted_traffic_end', models.TimeField(blank=True, null=True)),
                ('first_period_start', models.TimeField(blank=True, null=True)),
                ('first_period_end', models.TimeField(blank=True, null=True)),
                ('second_period_start', models.TimeField(blank=True, null=True)),
                ('second_period_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveSmallIntegerField(default=4730)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.BooleanField(blank=True, choices=[(True, 'آنلاین'), (False, 'آفلاین')], default=True, null=True, verbose_name='وضعیت دستگاه')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employer.attendancedevicebrand')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('image', models.ImageField(max_length=255, upload_to=base.models.get_file_path, verbose_name='عکس پروفایل')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='شماره همراه')),
                ('name', models.CharField(max_length=255, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=255, verbose_name='رمز عبور')),
                ('male_gender', models.BooleanField(blank=True, choices=[(True, 'آقا'), (False, 'خانم')], default=True, null=True, verbose_name='جنسیت')),
                ('personality', models.PositiveSmallIntegerField(choices=[(1, 'حقیقی'), (2, 'حقوقی')], default=1, verbose_name='نوع کاربری')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='تلفن')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)])),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('company_name', models.CharField(max_length=250)),
                ('company_registration_date', models.DateField(blank=True, null=True)),
                ('company_registration_number', models.PositiveIntegerField(blank=True, null=True)),
                ('branch_name', models.CharField(max_length=250)),
                ('economical_code', models.PositiveIntegerField(blank=True, null=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employer.employer')),
                ('legal_entity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employer.legalentitytype')),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField(blank=True, null=True)),
                ('shape', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'دایره'), (2, 'چند ضلعی')], default=1, null=True, verbose_name='شکل هندسی محل کار')),
                ('radius', models.PositiveSmallIntegerField(default=50, verbose_name='شعاع(متر)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='طول جغرافیایی')),
                ('BSSID', models.CharField(max_length=250)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.city')),
            ],
        ),
        migrations.CreateModel(
            name='WorkMissionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('acceptable_registration_days', models.PositiveSmallIntegerField()),
                ('maximum_request_per_year', models.PositiveSmallIntegerField()),
                ('maximum_request_per_month', models.PositiveSmallIntegerField()),
                ('acceptable_registration_type', models.PositiveSmallIntegerField(choices=[(1, 'قبل'), (2, 'بعد')], default=1)),
                ('acceptable_leave_registration_days', models.PositiveSmallIntegerField()),
                ('acceptable_hourly_registration_type', models.PositiveSmallIntegerField(choices=[(1, 'قبل'), (2, 'بعد')], default=1)),
                ('acceptable_hourly_leave_registration_days', models.PositiveSmallIntegerField()),
                ('work_policy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employer.workpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SickLeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('acceptable_registration_days', models.PositiveSmallIntegerField()),
                ('maximum_request_per_year', models.PositiveSmallIntegerField()),
                ('maximum_request_per_month', models.PositiveSmallIntegerField()),
                ('acceptable_registration_type', models.PositiveSmallIntegerField(choices=[(1, 'قبل'), (2, 'بعد')], default=1)),
                ('acceptable_leave_registration_days', models.PositiveSmallIntegerField()),
                ('acceptable_hourly_registration_type', models.PositiveSmallIntegerField(choices=[(1, 'قبل'), (2, 'بعد')], default=1)),
                ('acceptable_hourly_leave_registration_days', models.PositiveSmallIntegerField()),
                ('maximum_hourly_leave_request_per_year', models.PositiveSmallIntegerField()),
                ('maximum_hourly_leave_request_per_month', models.PositiveSmallIntegerField()),
                ('work_policy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employer.workpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OvertimePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('acceptable_registration_days', models.PositiveSmallIntegerField()),
                ('maximum_request_per_year', models.PositiveSmallIntegerField()),
                ('maximum_request_per_month', models.PositiveSmallIntegerField()),
                ('work_policy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employer.workpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManualTrafficPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('acceptable_registration_days', models.PositiveSmallIntegerField()),
                ('work_policy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employer.workpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EarnedLeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('acceptable_registration_days', models.PositiveSmallIntegerField()),
                ('maximum_request_per_year', models.PositiveSmallIntegerField()),
                ('maximum_request_per_month', models.PositiveSmallIntegerField()),
                ('acceptable_registration_type', models.PositiveSmallIntegerField(choices=[(1, 'قبل'), (2, 'بعد')], default=1)),
                ('acceptable_leave_registration_days', models.PositiveSmallIntegerField()),
                ('acceptable_hourly_registration_type', models.PositiveSmallIntegerField(choices=[(1, 'قبل'), (2, 'بعد')], default=1)),
                ('acceptable_hourly_leave_registration_days', models.PositiveSmallIntegerField()),
                ('maximum_hourly_leave_request_per_year', models.PositiveSmallIntegerField()),
                ('maximum_hourly_leave_request_per_month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('maximum_earned_leave_for_next_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('work_policy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employer.workpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
