# Generated by Django 5.0.2 on 2024-12-24 17:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
import employer.models
import phonenumber_field.modelfields
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='نام کاربری')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='شماره همراه')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceDeviceBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='employeeRequestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', django_jalali.db.models.jDateField()),
                ('floating_time', models.PositiveSmallIntegerField()),
                ('daily_overtime_limit', models.PositiveSmallIntegerField()),
                ('beginning_overtime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('middle_overtime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ending_overtime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('permitted_delay', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('permitted_acceleration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pre_shift_floating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('permitted_traffic_start', models.TimeField(blank=True, null=True)),
                ('permitted_traffic_end', models.TimeField(blank=True, null=True)),
                ('first_period_start', models.TimeField(blank=True, null=True)),
                ('first_period_end', models.TimeField(blank=True, null=True)),
                ('second_period_start', models.TimeField(blank=True, null=True)),
                ('second_period_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='کد ملی')),
                ('personnel_code', models.CharField(max_length=250)),
                ('shift_start_date', models.DateField()),
                ('shift_end_date', models.DateField()),
                ('use_gps', models.BooleanField(default=False)),
                ('use_wifi', models.BooleanField(default=False)),
                ('limit_devices', models.PositiveSmallIntegerField(choices=[(1, 'اپلیکیشن وب (pwa)'), (2, 'اپلیکیشن اندروید'), (3, 'هر دو نوع دستگاه (وب و اندروید)'), (4, 'دستگاه حضور و غیاب')], default=1)),
                ('interception', models.BooleanField(default=False)),
                ('work_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employer.workpolicy')),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employer.workshift')),
            ],
            options={
                'abstract': False,
            },
            bases=('employer.user',),
        ),
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveSmallIntegerField(default=4730)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.BooleanField(blank=True, choices=[(True, 'آنلاین'), (False, 'آفلاین')], default=True, null=True, verbose_name='وضعیت دستگاه')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employer.attendancedevicebrand')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employer.workcategory')),
                ('employee', models.ManyToManyField(to='employer.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField(blank=True, null=True)),
                ('shape', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'دایره'), (2, 'چند ضلعی')], default=1, null=True, verbose_name='شکل هندسی محل کار')),
                ('radius', models.PositiveSmallIntegerField(default=50, verbose_name='شعاع(متر)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='طول جغرافیایی')),
                ('BSSID', models.CharField(max_length=250)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.city')),
            ],
        ),
        migrations.CreateModel(
            name='WorkMissionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_hour_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_minute_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_hour_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_minute_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_daily_request_per_year', models.PositiveSmallIntegerField()),
                ('maximum_daily_request_per_month', models.PositiveSmallIntegerField()),
                ('maximum_hourly_request_per_year', models.PositiveSmallIntegerField()),
                ('maximum_hourly_request_per_month', models.PositiveSmallIntegerField()),
                ('acceptable_daily_registration_type', models.PositiveSmallIntegerField(choices=[(1, 'قبل'), (2, 'بعد')], default=1)),
                ('acceptable_daily_registration_days', models.PositiveSmallIntegerField()),
                ('acceptable_hourly_registration_type', models.PositiveSmallIntegerField(choices=[(1, 'قبل'), (2, 'بعد')], default=1)),
                ('acceptable_hourly_registration_days', models.PositiveSmallIntegerField()),
                ('work_policy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employer.workpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SickLeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_hour_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_minute_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_hour_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_minute_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_daily_request_per_year', models.PositiveSmallIntegerField()),
                ('maximum_daily_request_per_month', models.PositiveSmallIntegerField()),
                ('maximum_hourly_request_per_year', models.PositiveSmallIntegerField()),
                ('maximum_hourly_request_per_month', models.PositiveSmallIntegerField()),
                ('acceptable_daily_registration_type', models.PositiveSmallIntegerField(choices=[(1, 'قبل'), (2, 'بعد')], default=1)),
                ('acceptable_daily_registration_days', models.PositiveSmallIntegerField()),
                ('acceptable_hourly_registration_type', models.PositiveSmallIntegerField(choices=[(1, 'قبل'), (2, 'بعد')], default=1)),
                ('acceptable_hourly_registration_days', models.PositiveSmallIntegerField()),
                ('work_policy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employer.workpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OvertimePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_hour_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_minute_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_hour_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_minute_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_daily_request_per_year', models.PositiveSmallIntegerField()),
                ('maximum_daily_request_per_month', models.PositiveSmallIntegerField()),
                ('acceptable_registration_days', models.PositiveSmallIntegerField()),
                ('work_policy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employer.workpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManualTrafficPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('acceptable_registration_days', models.PositiveSmallIntegerField()),
                ('work_policy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employer.workpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='EarnedLeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_hour_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_minute_per_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_hour_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_minute_per_month', models.PositiveSmallIntegerField(help_text='minutes')),
                ('maximum_daily_request_per_year', models.PositiveSmallIntegerField()),
                ('maximum_daily_request_per_month', models.PositiveSmallIntegerField()),
                ('maximum_hourly_request_per_year', models.PositiveSmallIntegerField()),
                ('maximum_hourly_request_per_month', models.PositiveSmallIntegerField()),
                ('acceptable_daily_registration_type', models.PositiveSmallIntegerField(choices=[(1, 'قبل'), (2, 'بعد')], default=1)),
                ('acceptable_daily_registration_days', models.PositiveSmallIntegerField()),
                ('acceptable_hourly_registration_type', models.PositiveSmallIntegerField(choices=[(1, 'قبل'), (2, 'بعد')], default=1)),
                ('acceptable_hourly_registration_days', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('maximum_earned_leave_for_next_year', models.PositiveSmallIntegerField(help_text='minutes')),
                ('work_policy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employer.workpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RadkanMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employer.workcategory')),
                ('employee', models.ManyToManyField(to='employer.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.BooleanField()),
                ('employee', models.ManyToManyField(to='employer.employee')),
            ],
        ),
        migrations.CreateModel(
            name='employeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employer.employeerequestcategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employer.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employer.workplace'),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('national_code', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=employer.models.get_employer_image_file_path, verbose_name='عکس پروفایل')),
                ('male_gender', models.BooleanField(blank=True, choices=[(True, 'آقا'), (False, 'خانم')], default=True, null=True, verbose_name='جنسیت')),
                ('personality', models.PositiveSmallIntegerField(choices=[(1, 'حقیقی'), (2, 'حقوقی')], default=1, verbose_name='نوع کاربری')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='تلفن')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)])),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company_registration_date', models.DateField(blank=True, null=True)),
                ('company_registration_number', models.PositiveIntegerField(blank=True, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=250, null=True)),
                ('economical_code', models.PositiveIntegerField(blank=True, null=True)),
                ('legal_entity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employer.legalentitytype')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employer.employer')),
            ],
            options={
                'abstract': False,
            },
            bases=('employer.user',),
        ),
    ]
