# Generated by Django 5.0.2 on 2025-01-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedevice',
            name='is_online',
            field=models.BooleanField(blank=True, choices=[(True, 'آنلاین'), (False, 'آفلاین')], default=True, null=True, verbose_name='وضعیت دستگاه'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'در دست بررسی'), (2, 'تایید شده'), (3, 'رد شده')], default=1),
        ),
        migrations.AlterField(
            model_name='employer',
            name='personality',
            field=models.PositiveSmallIntegerField(choices=[(1, 'حقیقی'), (2, 'حقوقی')], default=1, verbose_name='نوع کاربری'),
        ),
        migrations.AlterField(
            model_name='workshiftplan',
            name='plan_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ساده'), (2, 'شناور')], default=1),
        ),
    ]
