# Generated by Django 5.0.2 on 2024-12-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earnedleavepolicy',
            name='acceptable_registration_days',
        ),
        migrations.RemoveField(
            model_name='overtimepolicy',
            name='acceptable_registration_days',
        ),
        migrations.RemoveField(
            model_name='sickleavepolicy',
            name='acceptable_registration_days',
        ),
        migrations.RemoveField(
            model_name='workmissionpolicy',
            name='acceptable_registration_days',
        ),
    ]
