# Generated by Django 5.0.2 on 2024-12-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='K', max_length=255, unique=True, verbose_name='نام کاربری'),
            preserve_default=False,
        ),
    ]
