# Generated by Django 5.0.2 on 2024-12-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_remove_earnedleavepolicy_acceptable_registration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimepolicy',
            name='acceptable_registration_days',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
