# Generated by Django 5.0.2 on 2025-01-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_manager_options_alter_workshift_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('employer', 'date')},
        ),
    ]
