# Generated by Django 5.0.2 on 2024-12-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_overtimepolicy_acceptable_registration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmissionpolicy',
            name='maximum_hourly_leave_request_per_month',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workmissionpolicy',
            name='maximum_hourly_leave_request_per_year',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
