# Generated by Django 5.0.2 on 2024-12-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
