# Generated by Django 5.1.4 on 2025-01-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_holiday_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollcall',
            name='arrival',
            field=models.TimeField(),
        ),
    ]
