# Generated by Django 5.0.2 on 2024-12-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_remove_earnedleavepolicy_acceptable_hourly_leave_registration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualtrafficpolicy',
            name='maximum_hour_per_month',
        ),
        migrations.RemoveField(
            model_name='manualtrafficpolicy',
            name='maximum_hour_per_year',
        ),
        migrations.RemoveField(
            model_name='manualtrafficpolicy',
            name='maximum_minute_per_month',
        ),
        migrations.RemoveField(
            model_name='manualtrafficpolicy',
            name='maximum_minute_per_year',
        ),
    ]
