# Generated by Django 5.1.4 on 2025-01-23 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_rollcall_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshiftplan',
            name='modifier',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='modifier', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='arrival',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
