# Generated by Django 5.1.4 on 2025-01-25 15:23

import employer.utilities
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_workshiftplan_modifier_alter_rollcall_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, validators=[employer.utilities.mobile_validator], verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=17, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=17, verbose_name='طول جغرافیایی'),
        ),
    ]
