# Generated by Django 5.0.2 on 2024-12-24 18:21

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='تلفن'),
        ),
    ]
