# Generated by Django 5.1.4 on 2025-01-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_employeerequest_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='email_employee_request_registered',
            field=models.BooleanField(default=False),
        ),
    ]
