# Generated by Django 5.0.2 on 2024-12-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_employer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='accepted_rules',
            field=models.BooleanField(default=False),
        ),
    ]
