# Generated by Django 5.1.4 on 2025-01-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_employer_email_employee_request_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnedleavepolicy',
            name='bypass_annual_limit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='earnedleavepolicy',
            name='bypass_monthly_limit',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AttendanceDevice',
        ),
    ]
