# Generated by Django 5.0.2 on 2024-12-24 21:51

import base.utilities
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_employer_accepted_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(default=base.utilities.get_random_int_code)),
                ('active', models.BooleanField(default=True)),
                ('request_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
