# Generated by Django 5.1.4 on 2025-01-28 11:01

import employer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_earnedleavepolicy_bypass_annual_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='down_image',
            field=models.ImageField(blank=True, null=True, upload_to=employer.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to=employer.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='front_second_image',
            field=models.ImageField(blank=True, null=True, upload_to=employer.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='left_image',
            field=models.ImageField(blank=True, null=True, upload_to=employer.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to=employer.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='up_image',
            field=models.ImageField(blank=True, null=True, upload_to=employer.models.get_file_path),
        ),
    ]
