# Generated by Django 5.1.4 on 2025-01-28 23:42

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_alter_employee_down_image_alter_employee_front_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceDeviceBrand',
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift_end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employer.workpolicy'),
        ),
    ]
