# Generated by Django 5.1.4 on 2025-01-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0011_delete_attendancedevicebrand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='employee',
            new_name='employees',
        ),
    ]
