# Generated by Django 5.1.4 on 2025-01-29 20:27

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0013_employer_city_employer_district_employer_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earnedleavepolicy',
            options={},
        ),
        migrations.CreateModel(
            name='EmployerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employer.employer')),
            ],
        ),
    ]
