# Generated by Django 5.1.4 on 2025-01-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0014_alter_earnedleavepolicy_options_employermessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'permissions': (('view_dashboard', 'Can view dashboard'),)},
        ),
    ]
