# Generated by Django 5.1.4 on 2025-02-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0015_alter_manager_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rollcall',
            old_name='latitude',
            new_name='arrival_latitude',
        ),
        migrations.RenameField(
            model_name='rollcall',
            old_name='longitude',
            new_name='arrival_longitude',
        ),
        migrations.AddField(
            model_name='rollcall',
            name='departure_latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='rollcall',
            name='departure_longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, verbose_name='طول جغرافیایی'),
        ),
    ]
