# Generated by Django 5.1.4 on 2025-02-14 13:02

import django_jalali.db.models
import employer.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0016_rename_latitude_rollcall_arrival_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollcall',
            name='arrival',
            field=models.TimeField(blank=True, null=True, validators=[employer.utilities.time_is_passed_validator]),
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='date',
            field=django_jalali.db.models.jDateField(validators=[employer.utilities.date_is_not_future_validator]),
        ),
        migrations.AlterField(
            model_name='rollcall',
            name='departure',
            field=models.TimeField(blank=True, null=True, validators=[employer.utilities.time_is_passed_validator]),
        ),
    ]
